[package]
name = "api-boiler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
actix-web = "4"
aws-config = "1.5.16"
aws-types = "1.3.5"
aws-sdk-s3 = "1.76.0"
bytes = "1"
